name: verifica-SOSEngasgo-edge
on:
#  push:
#    branches:
#      - 'master'
#  pull_request:
  workflow_dispatch:

jobs:
  teste_edge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cypress info
        uses: cypress-io/github-action@v6
        with:
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          # build: npm run info
          working-directory: examples/browser
          browser: edge
